// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RepRecApi.Database;

#nullable disable

namespace RepRecApi.Database.Migrations
{
    [DbContext(typeof(RepRecDbContext))]
    [Migration("20250107160621_PlanningTablesFK")]
    partial class PlanningTablesFK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RepRecApi.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LogLevelId")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("userId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LogLevelId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("RepRecApi.Models.LogLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LogLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Debug"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Info"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Warning"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Error"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Critical"
                        });
                });

            modelBuilder.Entity("RepRecApi.Models.OptExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Equipment")
                        .HasColumnType("text");

                    b.Property<string>("Force")
                        .HasColumnType("text");

                    b.Property<string>("Instructions")
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mechanic")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OptExerciseCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("PrimaryMuscles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondaryMuscles")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OptExerciseCategoryId");

                    b.ToTable("OptExercises");
                });

            modelBuilder.Entity("RepRecApi.Models.OptExerciseCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("JsonTemplate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OptExerciseCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Bodybuilding and Power-Lifting exercises",
                            JsonTemplate = "[]",
                            Name = "Weightlifting"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Snatch, Clean & Jerk, etc.",
                            JsonTemplate = "[]",
                            Name = "Olympic Lifting"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Atlas Stones, Tire Flips, etc.",
                            JsonTemplate = "[]",
                            Name = "Strongman"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Box Jumps, Jump Squats, etc.",
                            JsonTemplate = "[]",
                            Name = "Plyometrics"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Static, Dynamic, PNF, etc.",
                            JsonTemplate = "[]",
                            Name = "Stretching"
                        },
                        new
                        {
                            Id = 6,
                            Description = "All Forms of Cardio",
                            JsonTemplate = "[]",
                            Name = "Endurance Training"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Yoga, Pilates, Calisthenics, Courses, etc.",
                            JsonTemplate = "[]",
                            Name = "Physical Exercises"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Hiking, Swimming, Bouldering, Outdoor, etc.",
                            JsonTemplate = "[]",
                            Name = "Other Activities"
                        });
                });

            modelBuilder.Entity("RepRecApi.Models.PlanWorkout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PlanWorkouts");
                });

            modelBuilder.Entity("RepRecApi.Models.PlanWorkoutExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayIndex")
                        .HasColumnType("integer");

                    b.Property<int>("DayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ExerciseDefinitionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OptExerciseCategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("OptExerciseId")
                        .HasColumnType("integer");

                    b.Property<int>("PlanWorkoutId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OptExerciseCategoryId");

                    b.HasIndex("OptExerciseId");

                    b.HasIndex("PlanWorkoutId");

                    b.HasIndex("UserId");

                    b.ToTable("PlanWorkoutExercises");
                });

            modelBuilder.Entity("RepRecApi.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Planner"
                        },
                        new
                        {
                            Id = 3,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("RepRecApi.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RepRecApi.Models.UserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("RepRecApi.Models.Log", b =>
                {
                    b.HasOne("RepRecApi.Models.LogLevel", "LogLevel")
                        .WithMany("Logs")
                        .HasForeignKey("LogLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LogLevel");
                });

            modelBuilder.Entity("RepRecApi.Models.OptExercise", b =>
                {
                    b.HasOne("RepRecApi.Models.OptExerciseCategory", "OptExerciseCategory")
                        .WithMany("OptExercises")
                        .HasForeignKey("OptExerciseCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OptExerciseCategory");
                });

            modelBuilder.Entity("RepRecApi.Models.PlanWorkout", b =>
                {
                    b.HasOne("RepRecApi.Models.User", "User")
                        .WithMany("PlanWorkouts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RepRecApi.Models.PlanWorkoutExercise", b =>
                {
                    b.HasOne("RepRecApi.Models.OptExerciseCategory", "OptExerciseCategory")
                        .WithMany("PlanWorkoutExercises")
                        .HasForeignKey("OptExerciseCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepRecApi.Models.OptExercise", "OptExercise")
                        .WithMany("PlanWorkoutExercises")
                        .HasForeignKey("OptExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepRecApi.Models.PlanWorkout", "PlanWorkout")
                        .WithMany("PlanWorkoutExercises")
                        .HasForeignKey("PlanWorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepRecApi.Models.User", "User")
                        .WithMany("PlanWorkoutExercises")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OptExercise");

                    b.Navigation("OptExerciseCategory");

                    b.Navigation("PlanWorkout");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RepRecApi.Models.UserRole", b =>
                {
                    b.HasOne("RepRecApi.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepRecApi.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RepRecApi.Models.LogLevel", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("RepRecApi.Models.OptExercise", b =>
                {
                    b.Navigation("PlanWorkoutExercises");
                });

            modelBuilder.Entity("RepRecApi.Models.OptExerciseCategory", b =>
                {
                    b.Navigation("OptExercises");

                    b.Navigation("PlanWorkoutExercises");
                });

            modelBuilder.Entity("RepRecApi.Models.PlanWorkout", b =>
                {
                    b.Navigation("PlanWorkoutExercises");
                });

            modelBuilder.Entity("RepRecApi.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("RepRecApi.Models.User", b =>
                {
                    b.Navigation("PlanWorkoutExercises");

                    b.Navigation("PlanWorkouts");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
