# Step 1: Build the Angular app
FROM node:18 AS build-stage
WORKDIR /app
COPY repRec-frontend/package*.json ./
RUN npm install
COPY repRec-frontend/ ./
RUN npm run build --prod

# Step 2: Serve the app with Nginx
FROM nginx:alpine
COPY --from=build-stage /app/dist/rep-rec-frontend/browser /usr/share/nginx/html
COPY repRec-api/_docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
