version: '3.8'

services:
  frontend:
    build:
      context: ../..
      dockerfile: repRec-api/_docker/Dockerfile.frontend
    ports:
      - "8080:80"

  backend:
    build:
      context: ../..
      dockerfile: repRec-api/_docker/Dockerfile.backend
    ports:
      - "5205:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

networks:
  default:
    external:
      name: repRec_network
