# Step 1: Build the backend app
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY repRec-api/repRec-api.csproj ./
RUN dotnet restore
COPY repRec-api/ ./
RUN dotnet build -c Release -o /app

# Step 2: Publish the backend app
FROM build AS publish
RUN dotnet publish -c Release -o /app/publish

# Step 3: Run the app
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .
EXPOSE 80
ENTRYPOINT ["dotnet", "repRec-api.dll"]
